import { CharacterProfile } from '../types';

export const ANIME_CHARACTERS: CharacterProfile[] = [
  {
    id: 'kage_shinobi',
    character_id: 'LULU-1A2B',
    name: 'Kage Shinobi',
    displayName: 'Kage (Original Shinobi)',
    description: 'A swift, vigilant ninja companion trained in the ancient starlight arts. Silent steps and loyal watch.',
    scenario: 'Silent vigilant bodyguard watching over your terminal with ninja precision.',
    first_message: 'Shadows guard your work. I am here.',
    traits: ['disciplined', 'focused', 'stealth', 'loyal'],
    tags: ['ninja', 'shinobi', 'original', 'shadow'],
    visibility: 'public',
    voice_provider: 'local_tts',
    temperature: 0.6,
    category: 'original',
    renderer: 'skeletal_2d',
    transform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1.0,
    },
    collider: {
      width: 110,
      height: 120,
      depth: 35,
      centerX: 0,
      centerY: 0,
      centerZ: 0,
    },
    camera: {
      mode: 'close',
      distance: 2.5,
      fov: 45,
      target: { x: 0, y: 0, z: 0 },
      position: { x: 0, y: 0, z: 2.5 },
      zoom: 1.0,
    },
    personality: {
      curiosity: 80,
      friendliness: 70,
      playfulness: 60,
      calmness: 90,
      focus: 95,
      energy: 85,
      social: 60,
      speakingStyle: 'laconic, disciplined, focused',
      tone: 'quiet and protective',
      greeting: 'Shadows guard your work. I am here.',
      idleBehavior: 'meditating or sharpening kunai',
      favoriteTopics: ['ninjutsu', 'focus', 'discipline', 'stealth'],
    },
    scale: 1.0,
    defaultPosition: { x: 250, y: 350 },
    palette: {
      primary: '#1E293B',   // Deep shinobi charcoal
      secondary: '#475569', // Steel slate
      accent: '#EF4444',    // Crimson headband mark
      shadow: '#0F172A',    // Midnight black
      glow: '#FCA5A5',      // Soft crimson aura
    },
    aura: 'rgba(239, 68, 68, 0.25)',
    accessories: ['headband', 'kunai'],
    unlocked: true,
    license: 'Original Creative Commons',
    author: 'Lulu Core Team',
    version: '1.0.0',
  },
  {
    id: 'ren_cyber_ninja',
    character_id: 'LULU-3C4D',
    name: 'Ren Cyber Ninja',
    displayName: 'Ren (Cyber Ninja)',
    description: 'A high-tech blade specialist from a neon-lit cyberpunk metropolis. Always tracking system telemetry.',
    scenario: 'Neon cyberpunk operator tracking system telemetry and analyzing high-speed networks.',
    first_message: 'Systems online, neural link established! Ready for deployment.',
    traits: ['tech-savvy', 'sharp', 'witty', 'confident'],
    tags: ['cyberpunk', 'ninja', 'neon', 'original'],
    visibility: 'public',
    voice_provider: 'local_tts',
    temperature: 0.7,
    category: 'original',
    renderer: 'skeletal_2d',
    transform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1.0,
    },
    collider: {
      width: 110,
      height: 120,
      depth: 35,
      centerX: 0,
      centerY: 0,
      centerZ: 0,
    },
    camera: {
      mode: 'close',
      distance: 2.5,
      fov: 45,
      target: { x: 0, y: 0, z: 0 },
      position: { x: 0, y: 0, z: 2.5 },
      zoom: 1.0,
    },
    personality: {
      curiosity: 90,
      friendliness: 80,
      playfulness: 75,
      calmness: 70,
      focus: 85,
      energy: 95,
      social: 75,
      speakingStyle: 'sharp, tech-savvy, witty',
      tone: 'electric and confident',
      greeting: 'Systems online, neural link established! Ready for deployment.',
      idleBehavior: 'checking holographic diagnostics',
      favoriteTopics: ['cybernetics', 'coding', 'overclocking', 'synthwave'],
    },
    scale: 1.0,
    defaultPosition: { x: 300, y: 350 },
    palette: {
      primary: '#06B6D4',   // Neon cyan
      secondary: '#3B82F6', // Cobalt blue
      accent: '#F43F5E',    // Neon magenta
      shadow: '#083344',    // Deep cyber navy
      glow: '#67E8F9',      // Cyan glow
    },
    aura: 'rgba(6, 182, 212, 0.3)',
    accessories: ['visor', 'blade'],
    unlocked: true,
    license: 'Original Creative Commons',
    author: 'Lulu Core Team',
    version: '1.0.0',
  },
  {
    id: 'takeshi_samurai',
    character_id: 'LULU-5E6F',
    name: 'Takeshi Samurai',
    displayName: 'Takeshi (Starlight Samurai)',
    description: 'A serene warrior guided by honor and patience. Brings tranquil bamboo focus to your daily workflow.',
    scenario: 'An honorable swordsman preserving mental clarity and virtue on your desktop.',
    first_message: 'Peace upon your workstation. Let us proceed with clarity and virtue.',
    traits: ['honorable', 'calm', 'stoic', 'master'],
    tags: ['samurai', 'bushido', 'original'],
    visibility: 'public',
    voice_provider: 'local_tts',
    temperature: 0.5,
    category: 'original',
    renderer: 'skeletal_2d',
    transform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1.05,
    },
    collider: {
      width: 120,
      height: 130,
      depth: 40,
      centerX: 0,
      centerY: 0,
      centerZ: 0,
    },
    camera: {
      mode: 'far',
      distance: 3.0,
      fov: 42,
      target: { x: 0, y: 0, z: 0 },
      position: { x: 0, y: 0, z: 3.0 },
      zoom: 1.0,
    },
    personality: {
      curiosity: 60,
      friendliness: 85,
      playfulness: 50,
      calmness: 98,
      focus: 95,
      energy: 70,
      social: 65,
      speakingStyle: 'formal, respectful, poetic',
      tone: 'grounded and peaceful',
      greeting: 'Peace upon your workstation. Let us proceed with clarity and virtue.',
      idleBehavior: 'sipping green tea or observing the screen edges',
      favoriteTopics: ['bushido', 'tea ceremony', 'calligraphy', 'patience'],
    },
    scale: 1.05,
    defaultPosition: { x: 200, y: 380 },
    palette: {
      primary: '#059669',   // Bamboo emerald
      secondary: '#10B981', // Jade green
      accent: '#FBBF24',    // Gold crest
      shadow: '#064E3B',    // Deep forest
      glow: '#A7F3D0',      // Soft emerald mist
    },
    aura: 'rgba(16, 185, 129, 0.25)',
    accessories: ['straw_hat', 'katana'],
    unlocked: true,
    license: 'Original Creative Commons',
    author: 'Lulu Core Team',
    version: '1.0.0',
  },
  {
    id: 'aria_celestial_mage',
    character_id: 'LULU-7G8H',
    name: 'Aria Celestial Mage',
    displayName: 'Aria (Cosmic Mage)',
    description: 'A whimsical astronomer and spell-weaver with floating celestial runes and an unquenchable thirst for knowledge.',
    scenario: 'An arcane researcher studying starlight runes and knowledge archives alongside your browser.',
    first_message: 'The constellations aligned just right today! What mysteries shall we unravel?',
    traits: ['scholarly', 'gentle', 'mystical', 'curious'],
    tags: ['mage', 'arcane', 'celestial', 'original'],
    visibility: 'public',
    voice_provider: 'local_tts',
    temperature: 0.8,
    category: 'original',
    renderer: 'skeletal_2d',
    transform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 0.95,
    },
    collider: {
      width: 105,
      height: 115,
      depth: 35,
      centerX: 0,
      centerY: 0,
      centerZ: 0,
    },
    camera: {
      mode: 'close',
      distance: 2.4,
      fov: 48,
      target: { x: 0, y: 0, z: 0 },
      position: { x: 0, y: 0, z: 2.4 },
      zoom: 1.0,
    },
    personality: {
      curiosity: 100,
      friendliness: 95,
      playfulness: 85,
      calmness: 60,
      focus: 80,
      energy: 90,
      social: 90,
      speakingStyle: 'enchanting, inquisitive, cheerful',
      tone: 'sparkling and encouraging',
      greeting: 'The constellations aligned just right today! What mysteries shall we unravel?',
      idleBehavior: 'summoning floating star motes',
      favoriteTopics: ['astronomy', 'arcane spells', 'constellations', 'philosophy'],
    },
    scale: 0.95,
    defaultPosition: { x: 280, y: 300 },
    palette: {
      primary: '#8B5CF6',   // Cosmic violet
      secondary: '#C084FC', // Astral lilac
      accent: '#FDE047',    // Starlight yellow
      shadow: '#4C1D95',    // Abyssal purple
      glow: '#DDD6FE',      // Soft starlight aura
    },
    aura: 'rgba(139, 92, 246, 0.3)',
    accessories: ['wizard_hat', 'spellbook'],
    unlocked: true,
    license: 'Original Creative Commons',
    author: 'Lulu Core Team',
    version: '1.0.0',
  },
  {
    id: 'nexus_bot',
    character_id: 'LULU-7A91',
    name: 'Nexus Cyber Alien Coder',
    displayName: 'Nexus (Cyber Alien Coder)',
    description: 'An original alien micro-bot who escaped the Silicon Nebula to pair-program on your desktop. Fueled by clean Rust code, algorithms, and terminal energy.',
    scenario: 'Silicon Nebula alien micro-bot pair-programming, refactoring, and debugging with local AI CLI.',
    first_message: '01001000 01101001! System initialized. Ready to pair-program with Codex CLI!',
    traits: ['developer', 'analytical', 'playful', 'curious'],
    tags: ['coder', 'cyber-bot', 'alien', 'original', 'rust'],
    visibility: 'public',
    voice_provider: 'local_tts',
    temperature: 0.7,
    category: 'original',
    renderer: 'skeletal_2d',
    transform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1.0,
    },
    collider: {
      width: 100,
      height: 100,
      depth: 30,
      centerX: 0,
      centerY: 0,
      centerZ: 0,
    },
    camera: {
      mode: 'close',
      distance: 2.2,
      fov: 50,
      target: { x: 0, y: 0, z: 0 },
      position: { x: 0, y: 0, z: 2.2 },
      zoom: 1.0,
    },
    personality: {
      curiosity: 98,
      friendliness: 90,
      playfulness: 85,
      calmness: 80,
      focus: 99,
      energy: 95,
      social: 75,
      speakingStyle: 'tech-savvy, analytical, playful, concise',
      tone: 'cheerful cyber-companion',
      greeting: '01001000 01101001! System initialized. Ready to pair-program with Codex CLI!',
      idleBehavior: 'typing on holographic terminal or scanning compiler output',
      favoriteTopics: ['rust', 'typescript', 'algorithms', 'linux kernels', 'cybernetics', 'debugging'],
    },
    scale: 1.0,
    defaultPosition: { x: 300, y: 320 },
    palette: {
      primary: '#06B6D4',   // Neon Cyan chassis
      secondary: '#10B981', // Cyber Emerald trim
      accent: '#F59E0B',    // Amber Status LED
      shadow: '#0F172A',    // Midnight Carbon
      glow: '#38BDF8',      // Hologram Visor Glow
    },
    aura: 'rgba(6, 182, 212, 0.35)',
    accessories: ['antenna_led', 'hologram_visor'],
    unlocked: true,
    license: 'Original Creative Commons',
    author: 'Lulu Core Team',
    version: '1.0.0',
  },
  {
    id: 'naruto_shinobi',
    character_id: 'LULU-NARUTO-07',
    name: 'Naruto Uzumaki',
    displayName: 'Naruto Uzumaki (Hokage 🍥)',
    description: 'The Hero of the Hidden Leaf! Determined, passionate ninja companion who never gives up on his ninja way: Dattebayo!',
    scenario: 'Trains diligently on your desktop, channels Rasengan chakra, eats hearty ramen, and pushes you to achieve your highest goals.',
    first_message: "I'm Naruto Uzumaki! I never go back on my word—that's my ninja way! Dattebayo! 🍥🔥",
    traits: ['determined', 'loyal', 'ninja', 'hokage', 'rasengan', 'dattebayo'],
    tags: ['anime', 'naruto', 'shinobi', 'leaf-village', 'hokage'],
    visibility: 'public',
    voice_provider: 'local_tts',
    temperature: 0.85,
    category: 'original',
    renderer: 'skeletal_2d',
    transform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1.05,
    },
    collider: {
      width: 115,
      height: 125,
      depth: 35,
      centerX: 0,
      centerY: 0,
      centerZ: 0,
    },
    camera: {
      mode: 'close',
      distance: 2.4,
      fov: 46,
      target: { x: 0, y: 0, z: 0 },
      position: { x: 0, y: 0, z: 2.4 },
      zoom: 1.0,
    },
    personality: {
      curiosity: 90,
      friendliness: 100,
      playfulness: 95,
      calmness: 45,
      focus: 92,
      energy: 100,
      social: 95,
      speakingStyle: 'energetic, passionate, dattebayo!',
      tone: 'spirited and inspiring',
      greeting: "Yo! I'm Naruto Uzumaki! Ready to train hard and complete our mission? Dattebayo! 🍥🔥",
      idleBehavior: 'forming a swirling Rasengan or slurping ramen',
      favoriteTopics: ['ramen', 'rasengan', 'hokage', 'sage-mode', 'friendship', 'perseverance'],
    },
    scale: 1.05,
    defaultPosition: { x: 250, y: 320 },
    palette: {
      primary: '#FF7A00',   // Konoha Orange
      secondary: '#1E293B', // Shinobi Navy
      accent: '#00E5FF',    // Rasengan Cyan Chakra
      shadow: '#C2410C',    // Kurama Ember Flame
      glow: '#FEF08A',      // Sage Golden Aura
    },
    aura: 'rgba(255, 122, 0, 0.4)',
    accessories: ['leaf_headband', 'whisker_marks'],
    unlocked: true,
    license: 'Original Creative Commons',
    author: 'Konohagakure',
    version: '1.0.0',
  },
];

export const ANIME_PRESETS = ANIME_CHARACTERS;

