import { AnimationDefinition, AnimationState } from '../types';

export const ANIMATION_DEFINITIONS: Record<AnimationState, AnimationDefinition> = {
  idle: {
    id: 'idle',
    frames: 4,
    fps: 4,
    loopMode: 'ping-pong',
    priority: 1,
    interruptible: true,
    scale: 1.0,
  },
  walk: {
    id: 'walk',
    frames: 4,
    fps: 8,
    loopMode: 'loop',
    priority: 2,
    interruptible: true,
    scale: 1.0,
  },
  run: {
    id: 'run',
    frames: 4,
    fps: 12,
    loopMode: 'loop',
    priority: 3,
    interruptible: true,
    scale: 1.0,
  },
  sit: {
    id: 'sit',
    frames: 2,
    fps: 2,
    loopMode: 'loop',
    priority: 1,
    interruptible: true,
    scale: 1.0,
  },
  sleep: {
    id: 'sleep',
    frames: 4,
    fps: 2,
    loopMode: 'loop',
    priority: 5,
    interruptible: true,
    scale: 1.0,
  },
  wake: {
    id: 'wake',
    frames: 3,
    fps: 6,
    loopMode: 'once',
    priority: 4,
    interruptible: false,
    scale: 1.0,
  },
  curious: {
    id: 'curious',
    frames: 3,
    fps: 4,
    loopMode: 'ping-pong',
    priority: 3,
    interruptible: true,
    scale: 1.0,
  },
  happy: {
    id: 'happy',
    frames: 4,
    fps: 8,
    loopMode: 'loop',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  sad: {
    id: 'sad',
    frames: 2,
    fps: 2,
    loopMode: 'loop',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  surprised: {
    id: 'surprised',
    frames: 3,
    fps: 6,
    loopMode: 'ping-pong',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  confused: {
    id: 'confused',
    frames: 3,
    fps: 4,
    loopMode: 'ping-pong',
    priority: 3,
    interruptible: true,
    scale: 1.0,
  },
  excited: {
    id: 'excited',
    frames: 4,
    fps: 10,
    loopMode: 'loop',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  tired: {
    id: 'tired',
    frames: 2,
    fps: 2,
    loopMode: 'loop',
    priority: 3,
    interruptible: true,
    scale: 1.0,
  },
  playful: {
    id: 'playful',
    frames: 4,
    fps: 8,
    loopMode: 'loop',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  focus: {
    id: 'focus',
    frames: 2,
    fps: 2,
    loopMode: 'loop',
    priority: 2,
    interruptible: true,
    scale: 1.0,
  },
  celebrate: {
    id: 'celebrate',
    frames: 6,
    fps: 10,
    loopMode: 'loop',
    priority: 5,
    interruptible: false,
    scale: 1.0,
  },
  wave: {
    id: 'wave',
    frames: 4,
    fps: 6,
    loopMode: 'once',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  jump: {
    id: 'jump',
    frames: 4,
    fps: 10,
    loopMode: 'once',
    priority: 4,
    interruptible: false,
    scale: 1.0,
  },
  dance: {
    id: 'dance',
    frames: 6,
    fps: 8,
    loopMode: 'loop',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  eat: {
    id: 'eat',
    frames: 4,
    fps: 6,
    loopMode: 'once',
    priority: 4,
    interruptible: false,
    scale: 1.0,
  },
  drink: {
    id: 'drink',
    frames: 4,
    fps: 6,
    loopMode: 'once',
    priority: 4,
    interruptible: false,
    scale: 1.0,
  },
  listen: {
    id: 'listen',
    frames: 4,
    fps: 4,
    loopMode: 'ping-pong',
    priority: 2,
    interruptible: true,
    scale: 1.0,
  },
  yawn: {
    id: 'yawn',
    frames: 3,
    fps: 3,
    loopMode: 'once',
    priority: 3,
    interruptible: false,
    scale: 1.0,
  },
  read: {
    id: 'read',
    frames: 4,
    fps: 3,
    loopMode: 'loop',
    priority: 2,
    interruptible: true,
    scale: 1.0,
  },
  nod: {
    id: 'nod',
    frames: 3,
    fps: 5,
    loopMode: 'ping-pong',
    priority: 3,
    interruptible: true,
    scale: 1.0,
  },
  dizzy: {
    id: 'dizzy',
    frames: 4,
    fps: 6,
    loopMode: 'loop',
    priority: 4,
    interruptible: true,
    scale: 1.0,
  },
  meditate: {
    id: 'meditate',
    frames: 4,
    fps: 2,
    loopMode: 'ping-pong',
    priority: 2,
    interruptible: true,
    scale: 1.0,
  },
  pout: {
    id: 'pout',
    frames: 2,
    fps: 2,
    loopMode: 'ping-pong',
    priority: 3,
    interruptible: true,
    scale: 1.0,
  },
};
